# Generated by Django 6.0 on 2025-12-05 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_recepcion', models.TimeField()),
                ('hora_devolucion', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('firma_contratista', models.TextField(blank=True)),
                ('firma_instructor', models.TextField(blank=True)),
                ('firma_supervisor', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientes.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('SILLA', 'Silla'), ('MESA', 'Mesa'), ('COMPUTADOR', 'Computador'), ('MOUSE', 'Mouse'), ('TECLADO', 'Teclado'), ('TABLERO', 'Tablero')], max_length=20)),
                ('cantidad_esperada', models.IntegerField()),
                ('cantidad_actual', models.IntegerField()),
                ('estado', models.TextField(blank=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ambientes.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=20)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='ambientes.asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_usuario', models.CharField(choices=[('CONTRATISTA', 'Contratista'), ('INSTRUCTOR', 'Instructor'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrador')], max_length=20)),
                ('numero_identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('programa_formacion', models.CharField(max_length=200)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='ambientes.ambiente')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='contratista_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_contratista', to='ambientes.usuario'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_instructor', to='ambientes.usuario'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_supervisor', to='ambientes.usuario'),
        ),
    ]
